# Generated by Django 2.1.7 on 2019-03-25 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reflectsongs', '0004_auto_20190321_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='copyright_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
