# Generated by Django 2.1.7 on 2019-03-25 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reflectsongs', '0005_song_copyright_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='youtube_url',
            field=models.URLField(blank=True),
        ),
    ]
