# Generated by Django 2.1.7 on 2019-03-26 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reflectsongs', '0006_song_youtube_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='youtube_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
