# Generated by Django 2.1.7 on 2019-03-29 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reflectsongs', '0007_auto_20190326_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='slug',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
