# Generated by Django 2.2.1 on 2019-06-14 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reflectsongs', '0008_song_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='last_sync',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Sync'),
        ),
    ]
