# Generated by Django 2.2.2 on 2019-07-18 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reflectsongs', '0010_auto_20190708_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='lyrics',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='worshiptogether_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
