# Generated by Django 2.2.2 on 2019-07-28 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reflectsongs', '0015_chordresource'),
    ]

    operations = [
        migrations.AddField(
            model_name='chordresource',
            name='song_key',
            field=models.CharField(blank=True, choices=[('aflat', 'Ab'), ('a', 'A'), ('bflat', 'Bb'), ('b', 'B'), ('c', 'C'), ('csharp', 'C'), ('dflat', 'Db'), ('d', 'D'), ('eflat', 'Eb'), ('e', 'E'), ('f', 'F'), ('fsharp', 'F#'), ('gflat', 'Gb'), ('g', 'G')], max_length=5, null=True),
        ),
    ]
