# Generated by Django 2.2.2 on 2019-08-02 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reflectsongs', '0016_chordresource_song_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ('title',)},
        ),
    ]
