# Generated by Django 2.2.4 on 2019-10-18 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reflectsongs', '0018_song_all_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='setlist',
            name='pp_uid',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ProPresenter ID'),
        ),
    ]
