# Generated by Django 2.2.4 on 2019-10-21 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reflectsongs', '0020_auto_20191018_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setlist',
            name='songs',
            field=models.ManyToManyField(blank=True, related_name='setlists', to='reflectsongs.Song'),
        ),
    ]
