# Generated by Django 2.2.4 on 2019-11-27 20:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reflectsongs', '0021_auto_20191021_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='song',
            name='themes',
            field=models.ManyToManyField(blank=True, related_name='songs', to='reflectsongs.Theme'),
        ),
    ]
