# Generated by Django 2.2.4 on 2019-11-27 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reflectsongs', '0022_auto_20191127_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='copyright_info',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
