# Generated by Django 2.2.4 on 2019-11-28 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reflectsongs', '0023_song_copyright_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='slug',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
