# Generated by Django 2.2.10 on 2020-02-28 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reflectsongs', '0024_theme_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='setlist',
            name='import_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='setlist',
            name='source',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
