# Generated by Django 2.2.10 on 2020-05-02 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reflectsongs', '0026_set_import_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='copyright_info',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
